config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/one.html.erb
<h1>Gonzalo Salinas Espinoza</h1>

app/views/pages/three.html.erb
<h2>Titulo</h2>
<p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Eos molestiae ad, id dignissimos quibusdam temporibus alias consectetur voluptatum blanditiis debitis corporis repellat, delectus et! Doloremque omnis libero illo saepe ab.</p>

app/views/pages/two.html.erb
<h1>Esta es two</h1>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-inverse">
  <%= link_to "Navbar", root_path, class: 'navbar-brand' %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to 'One', pages_one_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Two', pages_two_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Three', pages_three_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>